Верстка шапки, главного экрана и путешествия
catch-a-chalk/1872127-antarctica pull request #1
Opened 2022-07-07 22:51 UTC by catch-a-chalk

2022-07-07 22:52 UTC, catch-a-chalk commented
![image](https://user-images.githubusercontent.com/84895122/177884445-5839a1e6-3c50-45c2-801d-dd67d3fd4308.png)
Не смог разобрать ошибку при выполнении editorconfig, что она значит?

2022-07-08 15:29 UTC, baileys-li commented
> Не смог разобрать ошибку при выполнении editorconfig, что она значит?
В операционных системах отличаются символы конца строки, но видимо либо ты, либо Гитхаб уже поправил.

2022-07-08 18:09 UTC, baileys-li requested changes

2022-07-08 18:09 UTC, baileys-li commented on build/index.html
> +      </section>
1. Список определений точно тут не нужен.
2. Заголовки можно опростить, потому что
    * клиент забьет их редактировать если будет нужно
    * у тебя все равно они повторяют информацию
3. **Не обязательно**: пусть фон будет фоном, но чтобы выполнить пожелание на управление им из html, мы будем менять инлайнить его и менять по кастом проперти в css. Но нужно будет проверить потом как парсят пути разные браузеры и адаптироваться под это.
4. Либо использовать `picture` но как БЭМ элемент. И не забыть поменять порядок подключение чтобы было desktop first
5. **Не обязательно**. Переименовать БЭМ блок
```suggestion
      <section class="intro" style="background-image: var(--bg, url(img/header-bg-desktop@1x.jpg)); 
        --double-bg: url(img/header-bg-desktop@2x.jpg); 
        --tab-bg: url(img/header-bg-tablet@1x.jpg); 
        --double-tab-bg: url(img/header-bg-desktop@2x.jpg); 
        --mob-bg: url(img/header-bg-mobile@1x.jpg); 
        --double-mob-bg: url(img/header-bg-mobile@2.jpg);">
      <div class="intro__wrapper">
        <h1 class="intro__title">Круизы в Антарктику</h1>
        <p class="intro__description">Волшебный мир айсбергов и пингвинов</p>
      </div>
    </section>
```

2022-07-08 18:49 UTC, baileys-li commented on source/index.html
>          <!-- Можем ли мы обыграть ту же самую навигацию, не вставляя её сюда повторно? -->
Нет, оно того не стоит. Лучше повторить

2022-07-08 19:16 UTC, baileys-li requested changes

2022-07-08 19:16 UTC, baileys-li commented on build/index.html
> +          </picture>
лучше поменять порядок на desktop first
```suggestion
         <picture>
          <source type="image/webp" media="(max-width: 500px)"  srcset="img/penguins-mobile@1x.webp, img/penguins-mobile@2x.webp 2x">
          <source type="image/jpg" media="(max-width: 500px)"  srcset="img/penguins-mobile@1x.jpg, img/penguins-mobile@2x.jpg 2x">
          <source type="image/webp" media="(max-width: 1200px)" srcset="img/penguins-tablet@1x.webp, img/penguins-tablet@2x.webp 2x">
          <source type="image/jpg" media="(max-width: 1200px)" srcset="img/penguins-tablet@1x.jpg, img/penguins-tablet@2x.jpg 2x">
          <source type="image/webp" srcset="img/penguins-desktop@1x.webp, img/penguins-desktop@2x.webp 2x">
          <img src="img/penguins-desktop@1x.jpg" srcset="img/penguins-desktop@2x.jpg 2x" alt="Пингвинчики">
        </picture>
```

2022-07-08 19:16 UTC, baileys-li commented on build/index.html
> +          <p class="main-advantages__title">Преимущества</p>
Аналогично
```suggestion
        <div class="main-advantages__wrapper">
          <h2 class="main-advantages__title">Преимущества</h2 >
```

2022-07-08 19:16 UTC, baileys-li commented on build/index.html
> +              </dl>
* декоративные иконки скрыть от Скрин ридера
* опять непонятный dl
```suggestion
              <svg class="main-advantages__logo" width="27" height="32" aria-hidden="true">
                <use href="img/sprite_auto.svg#logo-ship"></use>
              </svg>
              <h3 class="main-advantages__title">Небольшой круизный лайнер</h3>
              <p class="main-advantages__description">Круизный лайнер, рассчитанный всего лишь на 300 гостей, поможет избежать шума и очередей и даст возможность насладиться видами и природой.</p>
```

2022-07-08 19:16 UTC, baileys-li commented on build/index.html
> +            <div class="main-advantages__card">
необязательно
```suggestion
          <ul class="main-advantages__container">
            <!-- Вставить еще две карточки после утверждения формата -->
            <li class="main-advantages__card">
```

2022-07-08 19:16 UTC, baileys-li commented on build/index.html
> +        <h2 class="visually-hidden">Секция с контактами</h2>
Можно использовать семантический тэг. Просто без заголовка
```suggestion
      <address class="main-contacts">
```

2022-07-08 19:16 UTC, baileys-li commented on build/index.html
> +            <!-- Вставить иконку псевдоэлементом? -->
Можно и спрайтовый свг, просто не забыть про `aria-hidden="true"`

2022-07-10 13:35 UTC, merged